 CREATE DATABASE OPINION_CIUDADANA
USE OPINION_CIUDADANA

CREATE TABLE ADMINISTRADORES(
ID_ADMINISTRADOR INT PRIMARY KEY IDENTITY(1,1),
NOMBRE_ADMIN VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(50) NOT NULL,
CORREO_ELECTRONICO VARCHAR(100) NOT NULL,
CONTRASENA VARBINARY(500) NOT NULL
)

CREATE TABLE INFORMES(
	COD_INFORME INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(100) NOT NULL,
	RUTA_ARCHIVO VARCHAR(500) NOT NULL,
	FECHA_CREACION DATE NOT NULL,
	HORA_CREACION TIME NOT NULL,
	ID_ADMINISTRADOR INT REFERENCES ADMINISTRADORES(ID_ADMINISTRADOR)
)

CREATE TABLE SONDEOS(
	COD_SONDEO INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(100) NOT NULL,
	DESCRIPCION VARCHAR(100),
	TEMA VARCHAR(500) NOT NULL,
	FECHA_CREACION DATE NOT NULL,
	HORA_CREACION TIME NOT NULL,
	FECHA_FINAL DATE NOT NULL,
	HORA_FINAL TIME NOT NULL,
	RUTA_IMG VARCHAR(500),
	COD_INFORME INT REFERENCES INFORMES(COD_INFORME)
)

CREATE TABLE CIUDADANOS(
TIPO_DOCUMENTO VARCHAR(50) NOT NULL,
NUM_DOCUMENTO VARCHAR(15) PRIMARY KEY,
NOMBRES_COMPLETOS VARCHAR(100) NOT NULL,
APELLIDOS VARCHAR(100) NOT NULL,
SEXO VARCHAR(50) NOT NULL,
TELEFONO_CELULAR VARCHAR(12),
TELEFONO_FIJO VARCHAR(10),
CORREO_ELECTRONICO VARCHAR(100) NOT NULL,
MUNICIPIO VARCHAR(100) NOT NULL,
DIRECCION VARCHAR(200),
BARRIO_VEREDA VARCHAR (100) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
ETNIA VARCHAR(100) NOT NULL,
CONDICION_DISCAPACIDAD VARCHAR(200) NOT NULL,
ESTRATO_RESIDENCIA VARCHAR(2) NOT NULL,
NIVEL_EDUCATIVO VARCHAR(200) NOT NULL,
ACCESO_DISPOSITIVOS BIT NOT NULL,
TIPO_DISPOSITIVOS VARCHAR(50) NOT NULL,
CONECTIVIDAD BIT NOT NULL,
AFILIACION VARCHAR(50) NOT NULL
)

CREATE TABLE PARTICIPADORES_SONDEO(
	COD_SONDEO INT REFERENCES SONDEOS(COD_SONDEO),
	ID_CIUDADANO VARCHAR(15) REFERENCES CIUDADANOS(NUM_DOCUMENTO),
	FECHA_PART DATE NOT NULL,
	HORA_PART TIME NOT NULL,
)


CREATE TABLE CERTIFICADOS(
ID_CERTIFICADO VARCHAR(6) PRIMARY KEY,
FECHA_GENERACION DATE NOT NULL,
RUTA_ARCHIVO VARCHAR(500) NOT NULL,
NUM_DOCUMENTO VARCHAR(15) REFERENCES CIUDADANOS(NUM_DOCUMENTO)
)

CREATE TABLE PREGUNTAS(
COD_PREGUNTA INT PRIMARY KEY IDENTITY(1,1),
DESCRIPCION VARCHAR(500) NOT NULL
)

CREATE TABLE PREGUNTAS_DEL_SONDEO(
	COD_PREGUNTA INT REFERENCES PREGUNTAS(COD_PREGUNTA),
	COD_SONDEO INT REFERENCES SONDEOS(COD_SONDEO),
	RESPUESTA VARCHAR(500) DEFAULT NULL
)





